server:
  port: 7002
  servlet:
    context-path: /wificode

spring:
  application:
    name: wificode
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.nzhk.wificode

wificode:
  qrcode:
    storage-dir: /data/wificode/qrcode
  jwt:
    secret: ${wificode_JWT_SECRET}
  wechat:
    appid: ${wificode_WECHAT_APPID}
    secret: ${wificode_WECHAT_SECRET}
    check-path: true    # 生产环境校验 page 必须在已发布版本中存在
