server:
  port: 7002
  servlet:
    context-path: /wificode

spring:
  application:
    name: wificode
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://182.92.179.169:5432/wificode_test
    username: wificode_test
    password: wificode_test

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.nzhk.wificode

# 文件上传存储目录（相对或绝对路径）
wificode:
  file:
    storage-dir: E:/data/wificode/uploads
    base-url: /wificode/file/access
  qrcode:
    storage-dir: E:/data/wificode/qrcode
  jwt:
    secret: wificode
  wechat:
    appid: wx6120faf2f6e888c5
    secret: 19d0e002601704a421e64554aab42a1f
    check-path: false   # 开发环境不校验 page，便于未发布时生成小程序码
